### ISSUE TITLE
Fight Guides Roadmap: [endgame bosses, conquerors, shaper guardians, elder guardians, breachlords]

### ISSUE THREAD

**Issue by sbsrnt** [exile-watch/hideout#4]
#### Endgame Bosses
- [ ] Maven
    - [ ] data
    - [ ] media
- [ ] The Twins
    - [ ] data
    - [ ] media 
- [ ] Oshabi
    - [ ] data
    - [x] media
- [ ] Kosis
    - [ ] data
    - [ ] media
- [ ] Omniphobia
    - [ ] data
    - [x] media 
- [ ] Sirus
    - [ ] data
    - [x] media
- [ ] Cortex
    - [ ] data
    - [x] media
- [ ] Mastermind
    - [ ] data
    - [x] media
- [ ] Aul
    - [ ] data
    - [ ] media 
- [ ]  Elder
    - [ ] data
    - [x] media
- [ ] Shaper
    - [ ] data
    - [x] media 
- [ ] Uber Atziri
    - [ ] data
    - [x] media
- [ ] Atziri
    - [ ] data
    - [x] media

### Conquerors
- [ ] Baran
    - [ ] data
    - [x] media
- [ ] Verithania
    - [ ] data
    - [ ] media 
- [ ]  Al'Hezmin
    - [ ] data
    - [x] media
- [ ]  Drox
    - [ ] data
    - [x] media

### Shaper Guardians
- [ ] Guardian of the Phoenix
    - [x] data
    - [ ] media
- [x] Guardian of the Hydra
    - [x] data
    - [x] media 
- [x]  Guardian of the Minotaur
    - [x] data
    - [x] media
- [x]  Guardian of the Chimaera
    - [x] data
    - [x] media

### Elder Guardians
- [x]  The Purifier
    - [x] data
    - [x] media
- [x]  The Constrictor
    - [x] data
    - [x] media 
- [x]  The Enslaver
    - [x] data
    - [x] media
- [x] The Eradicator
    - [x] data
    - [x] media

### Breachlords
- [x] Xoph
    - [x] data
    - [x] media
- [x] Tul
    - [x] data
    - [x] media 
- [x] Esh
    - [x] data
    - [x] media
- [x] Uul-Netol
    - [x] data
    - [x] media
- [ ]  Chayula
    - [ ] data
    - [ ] media

### Abyss Liches
- [x] Stygian Spire
    - [x] data
    - [x] media
- [ ] Ulaman, Sovereign of the Well
    - [ ] data
    - [ ] media 
- [ ]  Amanamu, Liege of the Lightless
    - [ ] data
    - [ ] media
