### ISSUE TITLE
Features Roadmap: Encounters (Prod)

### ISSUE THREAD

**Issue by sbsrnt** [exile-watch/hideout#6]
# MVP
- [ ]  Fights with media
  - - [ ] exile-watch/hideout#4 (accepted for mvp: 100%)
  - - [ ] exile-watch/hideout#5 (accepted for mvp: 80%)
  - - [ ] exile-watch/hideout#3 (accepted for mvp: 80%)
  - - [ ] exile-watch/hideout#2 (accepted for mvp: 80%)
- [x]  Slick sidebar navigation
- [x]  Indexed Search of bosses and abilities
- [ ] Media / Page feedback button that redirects to issues page in order to create the issue
- [x] Homepage
- [x] Light theme
- [x] Short tour
- [x] Discord server for faster communications
- [ ] cookie banner (legal stuff)
- [ ] video enhancements/manipulation
  - - [ ] slow down
  - - [ ] pause/continue
  - - [ ] report issue
- [x] mobile version
- [x] add sitemap.xml for SEO

# POST MVP
- [ ] League challenges ability highlight
- [ ] League challenges boss highlight
- [ ] video enhancements/manipulation
  - - [ ] add sound indicator (not sure if feasible) 
  - - [ ] move around with click + mouse move
  - - [ ] zoom in/out
- [ ] act equivalent for every map boss that has it
- [ ] add `condition` tag to abilities that are present only when certain conditions are met (ex. 2 boss fight, one enrages after another is killed)
- [ ] add `deadly` tag for maps with rippy bosses (hi `vaal temple` and `precinct` with 5 bosses)
- [ ] add `auras` section for bosses that have them
- [ ] Background svg animation based on category we are in (sort of itemization theme we have for each influence) though
